CREATE TABLE LOAISP
(
	IDLOAI VARCHAR(6),
	TENLOAI NVARCHAR(100),
	PRIMARY KEY(IDLOAI)
)
GO

CREATE TABLE SANPHAM
(
	IDSP VARCHAR(6),
	TENSP NVARCHAR(100),
	IDLOAI VARCHAR(6),
	GIABAN FLOAT,
	GIANHAP FLOAT,
	SOLUONG INT,
	SIZE CHAR(2),
	TRANGTHAI BIT,
	PRIMARY KEY(IDSP),
	FOREIGN KEY(IDLOAI) REFERENCES LOAISP(IDLoai) ON UPDATE CASCADE ON DELETE CASCADE,
)
GO


CREATE TABLE KHACHHANG
(
	ID_KH VARCHAR(6),
	TEN_KH NVARCHAR(50),
	SDT_KH CHAR(10),
	DIACHI_KH NVARCHAR(100),
	PRIMARY KEY(ID_KH)
)
GO

CREATE TABLE NHANVIEN
(
	ID VARCHAR(6),
	TEN_NV NVARCHAR(50),
	GIOITINH BIT,
	CCCD CHAR(13),
	DIACHI_NV NVARCHAR(100),
	SDT_NV VARCHAR(10),
	CHUCVU NVARCHAR(20),
	PRIMARY KEY(ID)
)
GO

CREATE TABLE TAIKHOAN
(
	ID VARCHAR(6) UNIQUE,
	USERNAME VARCHAR(50),
	PASSWORD_USER NVARCHAR(2048),
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES NHANVIEN(ID) ON UPDATE CASCADE ON DELETE CASCADE,
)
GO

CREATE TABLE HOADON
(
	IDHD VARCHAR(6),
	NGAYTAO datetime,
	ID_USER VARCHAR(6),
	ID_KH VARCHAR(6),
	TONG_TIEN FLOAT,
	PRIMARY KEY(IDHD),
	FOREIGN KEY(ID_USER) REFERENCES NHANVIEN(ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(ID_KH) REFERENCES KHACHHANG(ID_KH) ON UPDATE CASCADE ON DELETE CASCADE
)
GO

CREATE TABLE CHITIET_HOADON
(
	IDHD VARCHAR(6),
	IDSP VARCHAR(6),
	SL int,
	TONGTIEN FLOAT,
	PRIMARY KEY(IDHD),
	FOREIGN KEY(IDHD) REFERENCES HOADON(IDHD) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(IDSP) REFERENCES SANPHAM(IDSP) ON UPDATE CASCADE ON DELETE CASCADE,
)
GO