
DELETE FROM CHITIET_HOADON;
DELETE FROM TAIKHOAN;
DELETE FROM HOADON;
DELETE FROM SANPHAM;
DELETE FROM NHANVIEN;
DELETE FROM LOAISP;

DROP TABLE IF EXISTS CHITIET_HOADON;
DROP TABLE IF EXISTS HOADON;
DROP TABLE IF EXISTS TAIKHOAN;
DROP TABLE IF EXISTS SANPHAM;
DROP TABLE IF EXISTS NHANVIEN;
DROP TABLE IF EXISTS LOAISP;
GO

CREATE TABLE LOAISP
(
	IDLOAI VARCHAR(6) PRIMARY KEY,
	TENLOAI NVARCHAR(100)
);
GO

CREATE TABLE SANPHAM
(
	IDSP VARCHAR(6) PRIMARY KEY,
	TENSP NVARCHAR(100),
	IDLOAI VARCHAR(6),
	GIABAN FLOAT,
	GIANHAP FLOAT,
	SOLUONG INT,
	SIZE NVARCHAR(3),
	TRANGTHAI BIT,
	FOREIGN KEY(IDLOAI) REFERENCES LOAISP(IDLOAI) ON UPDATE CASCADE ON DELETE CASCADE
);
GO

CREATE TABLE NHANVIEN
(
	ID VARCHAR(6) PRIMARY KEY,
	TEN_NV NVARCHAR(50),
	GIOITINH BIT,
	CCCD CHAR(13),
	DIACHI_NV NVARCHAR(100),
	SDT_NV VARCHAR(10),
	CHUCVU NVARCHAR(20)
);
GO

CREATE TABLE TAIKHOAN
(
	ID VARCHAR(6) PRIMARY KEY ,
	USERNAME VARCHAR(50),
	PASSWORD_USER NVARCHAR(2048),
	FOREIGN KEY(ID) REFERENCES NHANVIEN(ID) ON UPDATE CASCADE ON DELETE CASCADE
);
GO

CREATE TABLE HOADON
(
	IDHD VARCHAR(6) PRIMARY KEY,
	NGAYTAO DATETIME,
	ID_USER VARCHAR(6),
	TONG_TIEN FLOAT,
	FOREIGN KEY(ID_USER) REFERENCES NHANVIEN(ID) ON UPDATE CASCADE ON DELETE CASCADE
);
GO

CREATE TABLE CHITIET_HOADON
(
	IDHD VARCHAR(6),
	IDSP VARCHAR(6),
	SL INT,
	TONGTIEN FLOAT,
	PRIMARY KEY(IDHD, IDSP),
	FOREIGN KEY(IDHD) REFERENCES HOADON(IDHD) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(IDSP) REFERENCES SANPHAM(IDSP) ON UPDATE CASCADE ON DELETE CASCADE
);
GO


INSERT INTO NHANVIEN (ID, TEN_NV, GIOITINH, CCCD, DIACHI_NV, SDT_NV, CHUCVU)
VALUES ('QL0001', N'Hồ Ngọc Bảo', 1, '1234567890123', N'TP.HCM', '0123456789', N'Admin');
GO

INSERT INTO TAIKHOAN (ID, USERNAME, PASSWORD_USER)
VALUES ('QL0001', 'Admin', '123456');
GO

SELECT * FROM NHANVIEN
SELECT * FROM TAIKHOAN

INSERT INTO LOAISP (IDLOAI, TENLOAI)
VALUES ('BM', N'Bánh Mặn');
INSERT INTO LOAISP (IDLOAI, TENLOAI)
VALUES ('BN', N'Bánh Ngọt');
INSERT INTO LOAISP (IDLOAI, TENLOAI)
VALUES ('BC', N'Bánh Chay');


SELECT * FROM LOAISP
SELECT * FROM HOADON
SELECT * FROM CHITIET_HOADON